### PR TITLE
Feature/advanced fit

### PR DESCRIPTION
**Pull request by rhayes777**
Adds additional notebooks illustrating more advanced functionality.

2_advanced_autofit_example.ipynb 
Shows how more fields can be optimised. Expresses that c = 1 - (a + b) and also asserts that c > 0

3_multi_analysis.ipynb
Optimises multiple trail models simulatenously with a variable beta that is the same across all dates and a rho_q which is the same for all trails on a given date

### CODE REVIEW

**Comment by Jammy2211** [comment]
`data_directory = Path.cwd().parent.parent / "hst_acs_datasets"`

This does not produce a directory parallel to `warm_pixels` for me, but instead one up:

```
FileNotFoundError: [Errno 2] No such file or directory:`/mnt/c/Users/Jammy/Code/hst_acs_datasets/04_2017/jd5h08qoq_raw.fits`
```

**Comment by rjmassey** [comment]
Actually, where are the .json files used by 3_multi_analysis.ipynb produced, and how?
I have only pickle files in the cache directory.

**Comment by Jammy2211** [comment]
They are made here https://github.com/jkeger/warm_pixels/blob/feature/advanced_fit/notebooks/3_combine_with_autocti.ipynb

**Comment by Jammy2211** [comment]
Getting this after running the first tutorial:

```
Fit total trap densities... "10_2017" (2 of 2)            Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/scripts/tutorial_1_low_level_api.py", line 91, in <module>
    trap_densities = warm_pixels.all_trap_densities()
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/warm_pixels/model/cache.py", line 20, in wrapper
    self.__dict__[key] = func(self)
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/warm_pixels/__init__.py", line 52, in all_trap_densities
    return [
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/warm_pixels/__init__.py", line 53, in <listcomp>
    fu.fit_total_trap_densities(groups)
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/warm_pixels/hst_functions/fit.py", line 206, in fit_total_trap_densities
    rho_q, rho_q_std, y_fit = fit_dataset_total_trap_density(group)
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/warm_pixels/hst_functions/fit.py", line 119, in fit_dataset_total_trap_density
    stacked_lines = group.stacked_lines()
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/warm_pixels/model/cache.py", line 88, in wrapper
    result = func(instance)
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/warm_pixels/model/cache.py", line 20, in wrapper
    self.__dict__[key] = func(self)
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/warm_pixels/model/group.py", line 54, in stacked_lines
    return combined.generate_stacked_lines_from_bins(
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/warm_pixels/pixel_lines/collection.py", line 284, in generate_stacked_lines_from_bins
    row_bins = row_bins or self.row_bins()
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/warm_pixels/pixel_lines/collection.py", line 209, in row_bins
    self.locations[:, 0],
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by Jammy2211** [comment]
This for tutorial 2:

```
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/scripts/tutorial_2_high_level_api.py", line 56, in <module>
    plot.density()
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/warm_pixels/plot/__init__.py", line 100, in density
    trap_density_evol(
  File "/mnt/c/Users/Jammy/Code/PyAuto/warm_pixels/warm_pixels/plot/trap_density.py", line 178, in plot_trap_density_evol
    popt, pcov = curve_fit(
  File "/home/jammy/venvs/PyAuto/lib/python3.10/site-packages/scipy/optimize/_minpack_py.py", line 789, in curve_fit
    res = leastsq(func, p0, Dfun=jac, full_output=1, **kwargs)
  File "/home/jammy/venvs/PyAuto/lib/python3.10/site-packages/scipy/optimize/_minpack_py.py", line 414, in leastsq
    raise TypeError(f"Improper input: func input vector length N={n} must"
TypeError: Improper input: func input vector length N=2 must not exceed func output vector length M=1
```

**Comment by Jammy2211** [comment]
I have added python script versions of all the notebooks, these conform to the convention that allows our build tools auto-convert them into notebooks.

Once we have fully integrated `warm_pixels` into `autocti` we should move all these tutorials to the `autocti_workspace`. But I think we're a while off that yet, and keeping them separate is sufficient.

**Comment by rhayes777** [comment]
> `data_directory = Path.cwd().parent.parent / "hst_acs_datasets"`
> 
> This does not produce a directory parallel to `warm_pixels` for me, but instead one up:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory:`/mnt/c/Users/Jammy/Code/hst_acs_datasets/04_2017/jd5h08qoq_raw.fits`
> ```

It's relative to your current working directory

**Comment by rhayes777** [comment]
> Actually, where are the .json files used by 3_multi_analysis.ipynb produced, and how? I have only pickle files in the cache directory.

I thought I left one in the data directory although it was only a subset and you get much better results with a larger set. You can also generate them using the script:

```bash
./hst_warm_pixels.py directory --output stacked_lines

**Comment by rhayes777** [comment]
We could now also look at:
- Modelling the trap density as a function of time
- Using Message Passing to model trap density over time

**Pull request merged**
